"""Reconcile labeling function votes into silver labels.

Runs keyword LFs and (optionally) LLM LFs on all incidents, applies
confidence-weighted voting, writes silver labels to the incident_labels
table, and generates a weak-supervision report.

Usage:
    python -m scripts.reconcile_labels
    python -m scripts.reconcile_labels --with-llm --groq-api-key KEY
    python -m scripts.reconcile_labels --dry-run
"""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from app.core.db import create_engine, create_sessionmaker
from app.core.logging import configure_logging, get_logger
from app.core.settings import get_settings
from app.models.incident_label import TAXONOMY_LABELS
from app.repositories.incident import IncidentRepository
from app.repositories.incident_label import IncidentLabelRepository
from ml.weak_supervision.keyword_lfs import ALL_KEYWORD_LFS
from ml.weak_supervision.llm_lf import classify_with_llm, llm_results_to_lf_results
from ml.weak_supervision.types import IncidentRecord
from ml.weak_supervision.voter import (
    LabelVoter,
    build_conflict_matrix,
    compute_coverage,
)

logger = get_logger(__name__)


def _incident_to_record(inc: object) -> IncidentRecord:
    sections: dict[str, str] = {}
    raw_sections = getattr(inc, "sections", None)
    if isinstance(raw_sections, dict):
        sections = {str(k): str(v) for k, v in raw_sections.items()}
    elif isinstance(raw_sections, list):
        for s in raw_sections:
            if isinstance(s, str):
                sections[s] = s

    return IncidentRecord(
        content_hash=str(getattr(inc, "content_hash", "")),
        title=str(getattr(inc, "title", "")),
        summary=str(getattr(inc, "summary", "") or ""),
        body=str(getattr(inc, "summary", "") or ""),
        sections=sections,
        url=str(getattr(inc, "url", "") or ""),
        org=str(getattr(inc, "org", "")),
    )


def _generate_report(
    coverage: dict[str, int],
    conflict_matrix: dict[str, dict[str, float]],
    total_incidents: int,
    total_silver: int,
) -> str:
    lines = [
        "# Weak Supervision Report",
        "",
        f"**Total incidents:** {total_incidents}",
        f"**Incidents with ≥1 silver label:** {total_silver}",
        "",
        "## Per-Label Coverage",
        "",
        "| Label | Silver Positives | % of Corpus |",
        "|-------|-----------------|-------------|",
    ]
    for label in TAXONOMY_LABELS:
        count = coverage.get(label, 0)
        pct = round(100 * count / total_incidents, 1) if total_incidents > 0 else 0
        flag = " ⚠️" if count < 30 else ""
        lines.append(f"| `{label}` | {count} | {pct}%{flag} |")

    lines.extend(
        [
            "",
            "Labels with < 30 silver positives are flagged (⚠️) for review.",
            "",
            "## Co-occurrence Matrix (top diagonal)",
            "",
        ]
    )

    labels = list(TAXONOMY_LABELS)
    header = "| | " + " | ".join(f"`{lb[:8]}`" for lb in labels) + " |"
    sep = "|---" * (len(labels) + 1) + "|"
    lines.append(header)
    lines.append(sep)
    for a in labels:
        row_vals = []
        for b in labels:
            val = conflict_matrix.get(a, {}).get(b, 0.0)
            row_vals.append(f"{val:.2f}" if val > 0 else ".")
        lines.append(f"| `{a[:8]}` | " + " | ".join(row_vals) + " |")

    lines.extend(["", "---", "", "*Generated by `scripts/reconcile_labels.py`*", ""])
    return "\n".join(lines)


async def reconcile(
    *,
    with_llm: bool = False,
    groq_api_key: str | None = None,
    dry_run: bool = False,
    batch_size: int = 500,
) -> None:
    settings = get_settings()
    configure_logging(settings)
    engine = create_engine(settings)

    voter = LabelVoter(threshold=0.5, min_voters=1)
    all_records_votes: list[dict[str, dict[str, object]]] = []
    all_silver_lists: list[list[object]] = []
    total_incidents = 0

    try:
        sm = create_sessionmaker(engine)
        async with sm() as session:
            inc_repo = IncidentRepository(session)
            label_repo = IncidentLabelRepository(session)

            incidents = await inc_repo.list_all(limit=batch_size)
            total_incidents = len(incidents)
            logger.info("reconcile.start", total=total_incidents, with_llm=with_llm)

            for inc in incidents:
                record = _incident_to_record(inc)
                all_votes = voter.register_keyword_votes(record, ALL_KEYWORD_LFS)  # type: ignore[arg-type]

                if with_llm:
                    llm_result = classify_with_llm(record, api_key=groq_api_key)
                    llm_per_label = llm_results_to_lf_results(llm_result)
                    voter.register_llm_votes(all_votes, llm_per_label)

                vote_result = voter.vote(all_votes)
                all_records_votes.append(all_votes)  # type: ignore[arg-type]
                all_silver_lists.append(vote_result.silver_labels)  # type: ignore[arg-type]

                if not dry_run:
                    await label_repo.delete_by_source(inc.id, "weak")
                    for sl in vote_result.silver_labels:
                        await label_repo.upsert(
                            incident_id=inc.id,
                            label=sl.label,
                            source="weak",
                            confidence=sl.confidence,
                            annotator_id="weak_supervision",
                        )

            if not dry_run:
                await session.commit()

    finally:
        await engine.dispose()

    coverage = compute_coverage(all_silver_lists)  # type: ignore[arg-type]
    conflict_matrix = build_conflict_matrix(all_records_votes)  # type: ignore[arg-type]
    total_silver = sum(1 for sl in all_silver_lists if len(sl) > 0)

    report = _generate_report(coverage, conflict_matrix, total_incidents, total_silver)

    report_path = Path("docs/weak_supervision_report.md")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report)

    print(f"Reconciled {total_incidents} incidents → {total_silver} with silver labels")
    print(f"Report written to {report_path}")

    for label in TAXONOMY_LABELS:
        count = coverage.get(label, 0)
        status = "OK" if count >= 30 else "LOW"
        print(f"  {label}: {count} ({status})")


def main() -> None:
    parser = argparse.ArgumentParser(description="Reconcile LF votes into silver labels")
    parser.add_argument("--with-llm", action="store_true", help="Include LLM labeling")
    parser.add_argument("--groq-api-key", default=None, help="Groq API key")
    parser.add_argument("--dry-run", action="store_true", help="Don't write to DB")
    parser.add_argument("--batch-size", type=int, default=500)
    args = parser.parse_args()
    asyncio.run(
        reconcile(
            with_llm=args.with_llm,
            groq_api_key=args.groq_api_key,
            dry_run=args.dry_run,
            batch_size=args.batch_size,
        )
    )


if __name__ == "__main__":
    main()
